# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\JasmineJones\Documents\GuessingGame\YouLose.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from cmath import sqrt
from datetime import datetime
from random import random, uniform
from threading import Event
from xml.sax.handler import feature_external_ges
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QAbstractScrollArea, QWidget
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.units import inch
import openpyxl
import os
from reportlab.lib.pagesizes import letter
import textwrap
from reportlab.lib import colors
from datetime import datetime
import time
import Guess


class Ui_Form(object):

    def clicked_yes(self):
        

        ###open new Guess Window
        self.GuessWindow = QMainWindow()
        self.ui = Guess.Ui_MainWindow()
        self.ui.setupUi(self.GuessWindow)
        self.GuessWindow.show()

        #ui = Ui_Form()
        self.LostWindow = QWidget()
        LostWindow.close()

    def clicked_no(self):
        LostWindow.close()

    def setupUi(self, Form, count):
        Form.setObjectName("Form")
        Form.resize(267, 170)
        Form.setMinimumSize(QtCore.QSize(267, 170))
        Form.setMaximumSize(QtCore.QSize(267, 170))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(14)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setAutoFillBackground(False)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.gridLayout.addWidget(self.Title, 1, 3, 1, 1)

        self.yes = QtWidgets.QPushButton(Form)
        self.yes.setObjectName("yes")
        self.gridLayout.addWidget(self.yes, 14, 3, 1, 1)
        self.yes.clicked.connect(self.clicked_yes)

        self.no = QtWidgets.QPushButton(Form)
        self.no.setObjectName("no")
        self.gridLayout.addWidget(self.no, 15, 3, 1, 1)
        self.no.clicked.connect(self.clicked_no)
        
        self.roundLabel = QtWidgets.QLabel(Form)
        self.roundLabel.setObjectName("roundLabel")
        self.gridLayout.addWidget(self.roundLabel, 3, 3, 1, 1)
        self.rounds = QtWidgets.QTextBrowser(Form)
        self.rounds.setEnabled(True)
        self.rounds.setMaximumSize(QtCore.QSize(50, 25))
        self.rounds.setObjectName("rounds")
        self.rounds.setText(str(count))
        self.gridLayout.addWidget(self.rounds, 4, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "You Lose! Retry?"))
        self.yes.setText(_translate("Form", "Yes"))
        self.no.setText(_translate("Form", "No"))
        #self.rounds.setText(_translate("Form", count))
        self.roundLabel.setText(_translate("Form", "Rounds:"))

if __name__ == "__main__": #### Creates Scene ####
    import sys
    app = QApplication(sys.argv)
    ui = Ui_Form()
    LostWindow = QWidget()
    ui.setupUi(LostWindow)
    LostWindow.show()
    sys.exit(app.exec())
